-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (SUM(S.SALES * B.PRICE)) AS TOTAL_SALES
FROM BOOK AS B 
    JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID 
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY 1, 3 DESC;