-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, 
ROUND(C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100) * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
)
AND P.DURATION_TYPE = '30일 이상'
AND ROUND(C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;