-- 코드를 작성해주세요
SELECT A.ID, 
    CASE
        WHEN B.PCT <= 0.25 THEN 'CRITICAL'
        WHEN B.PCT <= 0.5 THEN 'HIGH'
        WHEN B.PCT <= 0.75 THEN 'MEDIUM'
        WHEN B.PCT <= 1 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA AS A JOIN (
        SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
        FROM ECOLI_DATA
    ) AS B
    ON A.ID = B.ID
ORDER BY 1;