-- 코드를 작성해주세요
SELECT ID,
    CASE
        WHEN R_RANK <= (0.25 * R_COUNT) THEN 'CRITICAL'
        WHEN R_RANK <= (0.50 * R_COUNT) THEN 'HIGH'
        WHEN R_RANK <= (0.75 * R_COUNT) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT *, 
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R_RANK,
        COUNT(*) OVER () AS R_COUNT
    FROM ECOLI_DATA
) AS RANK_INFO
ORDER BY ID;