-- 코드를 입력하세요
WITH RENTAL_HISTORY AS (
    SELECT 
        HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS, 
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상' 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT H.HISTORY_ID, 
    CASE 
        WHEN H.DURATION_TYPE IS NULL THEN ROUND(H.RENTAL_DAYS * C.DAILY_FEE)
        ELSE ROUND(H.RENTAL_DAYS * C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) 
    END AS FEE
FROM RENTAL_HISTORY AS H 
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON H.DURATION_TYPE = P.DURATION_TYPE
    AND P.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;