-- 코드를 작성해주세요
SELECT R.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E 
JOIN (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY SCORE DESC
        LIMIT 1
) AS R
ON E.EMP_NO = R.EMP_NO;