-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = "세단" AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC;